### ISSUE TITLE
Prática 1 / Parte 3 - Passo 3 (Criar uma issue para o professor adicionar nome como colaborador)

### ISSUE THREAD

**Issue by mecarolme** [mecarolme/GCMS-Caroline-Medeiros#1]
Adicionar aqui -> [README](https://github.com/mecarolme/GCMS-Caroline-Medeiros/edit/main/README.md)

**Comment by ramidedantas** [comment]
@mecarolme Coloque o README no mesmo formato que está no meu repositório e depois me marque aqui.

**Comment by mecarolme** [comment]
@ramidedantas está ok agora?

**Comment by ramidedantas** [comment]
@mecarolme agora está sim, pode fechar a issue.
